export type Field = { name: string; label: string; type?: "text" | "number" | "date" | "select" | "textarea"; required?: boolean; source?: string; options?: string[]; step?: string };
export type Section = { title: string; table: string; id: string; fields: Field[]; action?: string; adminOnly?: boolean; master?: boolean; columns: string[] };
const date: Field = { name: "tanggal", label: "Tanggal", type: "date", required: true };
const note: Field = { name: "keterangan", label: "Keterangan", type: "textarea" };
const cage: Field = { name: "id_kandang", label: "Kandang", type: "select", source: "kandang", required: true };
const feed: Field = { name: "id_pakan", label: "Pakan", type: "select", source: "pakan", required: true };
const egg: Field = { name: "id_kategori_telur", label: "Kategori telur", type: "select", source: "kategori_telur", required: true };
const num = (name: string, label: string, step = "1"): Field => ({ name, label, type: "number", step, required: true });
export const sections: Record<string, Section> = {
  "peternakan/kandang": { title: "Kandang", table: "kandang", id: "id_kandang", master: true, fields: [{ name: "nama_kandang", label: "Nama kandang", required: true }, note], columns: ["nama_kandang", "keterangan"] },
  "peternakan/kategori-ternak": { title: "Kategori ternak", table: "kategori_ternak", id: "id_kategori_ternak", master: true, fields: [{ name: "nama_kategori", label: "Nama kategori", required: true }], columns: ["nama_kategori"] },
  "peternakan/populasi": { title: "Populasi ternak", table: "v_populasi_aktif", id: "id_populasi", action: "create_population", fields: [cage, { name: "id_kategori_ternak", label: "Kategori ternak", type: "select", source: "kategori_ternak", required: true }, { ...date, name: "tanggal_masuk" }, num("jumlah_awal", "Jumlah awal"), num("usia_masuk", "Usia masuk"), { name: "ras", label: "Ras" }, note], columns: ["tanggal_masuk", "jumlah_awal", "jumlah_aktif", "id_kandang", "id_kategori_ternak"] },
  "pakan/master": { title: "Master pakan", table: "pakan", id: "id_pakan", master: true, fields: [{ name: "nama_pakan", label: "Nama pakan", required: true }, { name: "jenis_pakan", label: "Jenis", type: "select", options: ["BAHAN_BAKU", "PAKAN_JADI", "HASIL_CAMPURAN"], required: true }, { name: "satuan", label: "Satuan", options: ["kg"], type: "select", required: true }], columns: ["nama_pakan", "jenis_pakan", "satuan"] },
  "pakan/masuk": { title: "Pakan masuk", table: "pakan_masuk", id: "id_pakan_masuk", action: "create_feed_receipt", fields: [feed, date, num("berat_kg", "Berat (kg)", "0.001"), num("harga_total", "Harga total (Rp)", "0.01"), note], columns: ["tanggal", "id_pakan", "berat_kg", "harga_total", "keterangan"] },
  "pakan/mix": { title: "Mix pakan", table: "mix_pakan", id: "id_mix", action: "create_feed_mix", fields: [date, { name: "nama_mix", label: "Nama mix", required: true }, { name: "id_pakan_hasil", label: "Pakan hasil", type: "select", source: "pakan", required: true }], columns: ["tanggal", "nama_mix", "id_pakan_hasil", "total_berat", "total_biaya"] },
  "pakan/keluar": { title: "Pengeluaran pakan", table: "pengeluaran_pakan", id: "id_pakan_keluar", action: "create_feed_issue", fields: [feed, { ...cage, required: false }, date, num("jumlah_kg", "Jumlah (kg)", "0.001"), { name: "tujuan", label: "Tujuan", required: true }, note], columns: ["tanggal", "id_pakan", "id_kandang", "jumlah_kg", "tujuan"] },
  "pakan/stok": { title: "Stok pakan", table: "v_stok_pakan", id: "id_pakan", fields: [], columns: ["nama_pakan", "jenis_pakan", "stok_kg"] },
  "telur/panen": { title: "Panen telur", table: "panen", id: "id_panen", action: "create_harvest", fields: [cage, date, num("jumlah_utuh", "Telur utuh"), num("jumlah_retak", "Telur retak"), num("berat_utuh_kg", "Berat utuh (kg)", "0.001"), note], columns: ["tanggal", "id_kandang", "jumlah_utuh", "jumlah_retak", "berat_utuh_kg"] },
  "telur/kategori": { title: "Kategori telur", table: "kategori_telur", id: "id_kategori_telur", master: true, fields: [{ name: "nama_kategori", label: "Nama kategori", required: true }], columns: ["nama_kategori"] },
  "telur/sortir": { title: "Sortir telur", table: "panen", id: "id_panen", action: "sort_harvest", fields: [{ name: "id_panen", label: "Panen", type: "select", source: "panen", required: true }], columns: ["tanggal", "jumlah_utuh", "jumlah_retak"] },
  "telur/distribusi": { title: "Distribusi telur", table: "distribusi_telur", id: "id_distribusi", action: "create_egg_distribution", fields: [date, { name: "tujuan_pembeli", label: "Tujuan pembeli", required: true }, note], columns: ["tanggal", "tujuan_pembeli", "total_harga"] },
  "telur/stok": { title: "Stok telur", table: "v_stok_telur", id: "id_kategori_telur", fields: [], columns: ["nama_kategori", "stok_telur"] },
  "keuangan/kategori": { title: "Kategori keuangan", table: "kategori_keuangan", id: "id_kategori_keuangan", adminOnly: true, master: true, fields: [{ name: "nama_kategori", label: "Nama kategori", required: true }, { name: "tipe", label: "Tipe", type: "select", options: ["PEMASUKAN", "PENGELUARAN"], required: true }], columns: ["nama_kategori", "tipe"] },
  "keuangan/transaksi": { title: "Transaksi keuangan", table: "transaksi_keuangan", id: "id_transaksi", action: "create_manual_finance", adminOnly: true, fields: [{ name: "tipe", label: "Tipe", type: "select", options: ["PEMASUKAN", "PENGELUARAN"], required: true }, { name: "id_kategori_keuangan", label: "Kategori keuangan", type: "select", source: "kategori_keuangan", required: true }, date, num("nominal", "Nominal (Rp)", "0.01"), note], columns: ["tanggal", "id_kategori_keuangan", "nominal", "keterangan"] },
};
export const optionLabel: Record<string, string> = { kandang: "nama_kandang", kategori_ternak: "nama_kategori", pakan: "nama_pakan", kategori_telur: "nama_kategori", kategori_keuangan: "nama_kategori", panen: "tanggal" };
export const optionId: Record<string, string> = { kandang: "id_kandang", kategori_ternak: "id_kategori_ternak", pakan: "id_pakan", kategori_telur: "id_kategori_telur", kategori_keuangan: "id_kategori_keuangan", panen: "id_panen" };
export const eggField = egg;
