"use client";
import { useState } from "react";
import { useFormStatus } from "react-dom";
import Link from "next/link";
import type { Role } from "@/lib/auth";
import type { Field, Section } from "@/lib/sections";
import { cancelSection, saveSection } from "./actions";

type Props = { path: string; config: Section; rows: Record<string, unknown>[]; options: Record<string, { id: string; label: string }[]>; role: Role; search: { q?: string; from?: string; to?: string; error?: string; success?: string }; loadError: boolean };
function Submit({ label }: { label: string }) { const { pending } = useFormStatus(); return <button disabled={pending} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50">{pending ? "Menyimpan..." : label}</button>; }
function Input({ field, options, defaultValue }: { field: Field; options: Props["options"]; defaultValue?: string }) {
  const cls = "mt-1 w-full rounded-md border bg-background p-2 text-sm";
  return <label className="block text-sm font-medium">{field.label}{field.type === "select" ? <select name={field.name} required={field.required} defaultValue={defaultValue || ""} className={cls}><option value="">Pilih {field.label.toLowerCase()}</option>{(field.source ? options[field.source] || [] : (field.options || []).map(x => ({ id: x, label: x }))).map(x => <option key={x.id} value={x.id}>{x.label}</option>)}</select> : field.type === "textarea" ? <textarea name={field.name} defaultValue={defaultValue} className={cls} /> : <input name={field.name} type={field.type || "text"} step={field.step} min={field.type === "number" ? 0 : undefined} required={field.required} defaultValue={defaultValue ?? (field.type === "date" ? new Date().toISOString().slice(0,10) : "")} className={cls} />}</label>;
}
export function SectionView({ path, config, rows, options, role, search, loadError }: Props) {
  const [editing, setEditing] = useState<Record<string, unknown> | null>(null);
  const [details, setDetails] = useState([{ id_pakan: "", berat_bahan: "", id_kategori_telur: "", jumlah_telur: "", harga_satuan: "" }]);
  const canWrite = role === "Administrator" || (role === "ABK" && !config.master && !config.adminOnly && !config.finance);
  const detailKind = path === "pakan/mix" ? "mix" : path === "telur/sortir" ? "sortir" : path === "telur/distribusi" ? "distribusi" : null;
  const detailOptions = detailKind === "mix" ? options.pakan : options.kategori_telur;
  const filteredRows = search.q ? rows.filter(row => Object.values(row).some(x => String(x ?? "").toLowerCase().includes(search.q!.toLowerCase()))) : rows;
  const formAction = saveSection.bind(null, path);
  return <div className="space-y-6">
    <div><h1 className="text-2xl font-semibold">{config.title}</h1><p className="text-sm text-muted-foreground">{filteredRows.length} data ditampilkan</p></div>
    {search.error && <p role="alert" className="rounded-md border border-destructive p-3 text-sm text-destructive">{search.error}</p>}
    {search.success && <p role="status" className="rounded-md border p-3 text-sm">{search.success}</p>}
    {loadError && <p role="alert" className="text-sm text-destructive">Data gagal dimuat. Periksa koneksi dan migration.</p>}
    {canWrite && config.fields.length > 0 && <form action={formAction} className="rounded-lg border p-4">
      <h2 className="mb-4 font-semibold">{editing ? "Ubah data" : "Tambah data"}</h2>
      <input type="hidden" name="_operation" value={editing ? "edit" : "create"} /><input type="hidden" name="_id" value={editing ? String(editing[config.id]) : ""} />
      <div className="grid gap-4 sm:grid-cols-2">{config.fields.map(field => <Input key={`${field.name}-${String(editing?.[config.id] || "new")}`} field={field} options={options} defaultValue={editing ? String(editing[field.name] ?? "") : undefined} />)}</div>
      {detailKind && <div className="mt-4 space-y-3"><h3 className="font-medium">Detail {detailKind}</h3>{details.map((item, index) => <div key={index} className="grid gap-2 rounded-md border p-3 sm:grid-cols-3"><select required value={detailKind === "mix" ? item.id_pakan : item.id_kategori_telur} onChange={e => setDetails(old => old.map((x,i) => i===index ? { ...x, [detailKind === "mix" ? "id_pakan" : "id_kategori_telur"]: e.target.value } : x))} className="rounded-md border p-2 text-sm"><option value="">Pilih {detailKind === "mix" ? "pakan" : "kategori telur"}</option>{(detailOptions || []).map(x => <option value={x.id} key={x.id}>{x.label}</option>)}</select><input required type="number" min="0.001" step={detailKind === "mix" ? "0.001" : "1"} placeholder={detailKind === "mix" ? "Berat kg" : "Jumlah telur"} value={detailKind === "mix" ? item.berat_bahan : item.jumlah_telur} onChange={e => setDetails(old => old.map((x,i) => i===index ? { ...x, [detailKind === "mix" ? "berat_bahan" : "jumlah_telur"]: e.target.value } : x))} className="rounded-md border p-2 text-sm" />{detailKind === "distribusi" && <input required type="number" min="0" step="0.01" placeholder="Harga satuan" value={item.harga_satuan} onChange={e => setDetails(old => old.map((x,i) => i===index ? { ...x, harga_satuan: e.target.value } : x))} className="rounded-md border p-2 text-sm" />}{details.length>1 && <button type="button" className="text-sm underline" onClick={() => setDetails(old => old.filter((_,i) => i!==index))}>Hapus detail</button>}</div>)}<button type="button" className="text-sm underline" onClick={() => setDetails(old => [...old, { id_pakan:"",berat_bahan:"",id_kategori_telur:"",jumlah_telur:"",harga_satuan:"" }])}>+ Tambah detail</button><input type="hidden" name="_details" value={JSON.stringify(details.map(x => detailKind === "mix" ? { id_pakan:x.id_pakan,berat_bahan:Number(x.berat_bahan) } : detailKind === "sortir" ? { id_kategori_telur:x.id_kategori_telur,jumlah_telur:Number(x.jumlah_telur) } : { id_kategori_telur:x.id_kategori_telur,jumlah_telur:Number(x.jumlah_telur),harga_satuan:Number(x.harga_satuan) }))} /></div>}
      <div className="mt-4 flex gap-2"><Submit label={editing ? "Simpan perubahan" : "Simpan"} />{editing && <button type="button" className="rounded-md border px-4 py-2 text-sm" onClick={() => setEditing(null)}>Batal</button>}</div>
    </form>}
    <form className="flex flex-wrap gap-2"><input name="q" defaultValue={search.q} placeholder="Cari data" className="rounded-md border p-2 text-sm" />{config.columns.some(x => x === "tanggal" || x === "tanggal_masuk") && <><input name="from" type="date" defaultValue={search.from} className="rounded-md border p-2 text-sm" /><input name="to" type="date" defaultValue={search.to} className="rounded-md border p-2 text-sm" /></>}<button className="rounded-md border px-3 text-sm">Filter</button></form>
    <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-muted"><tr>{config.columns.map(column => <th key={column} className="p-3">{column.replaceAll("_"," ")}</th>)}{(config.master && canWrite || path === "peternakan/populasi" || (role === "Administrator" && ["pakan/masuk","pakan/mix","pakan/keluar","telur/panen","telur/distribusi","keuangan/transaksi"].includes(path))) && <th className="p-3">Aksi</th>}</tr></thead><tbody>{filteredRows.map(row => <tr key={String(row[config.id])} className="border-t">{config.columns.map(column => <td key={column} className="p-3">{options[column.replace(/^id_/,"")]?.find(x => x.id === row[column])?.label || String(row[column] ?? "-")}</td>)}{(config.master && canWrite || path === "peternakan/populasi" || (role === "Administrator" && ["pakan/masuk","pakan/mix","pakan/keluar","telur/panen","telur/distribusi","keuangan/transaksi"].includes(path))) && <td className="p-3">{config.master && canWrite ? <div className="flex gap-3"><button type="button" className="underline" onClick={() => { setEditing(row); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Edit</button><form action={formAction} onSubmit={e => { if (!window.confirm("Hapus data ini?")) e.preventDefault(); }}><input type="hidden" name="_operation" value="delete" /><input type="hidden" name="_id" value={String(row[config.id])} /><button className="text-destructive underline">Hapus</button></form></div> : path === "peternakan/populasi" ? <Link className="underline" href={`/peternakan/populasi/${row.id_populasi}`}>Detail</Link> : <form action={cancelSection.bind(null,path,String(row[config.id]))} onSubmit={e => { if (!window.confirm("Batalkan transaksi ini?")) e.preventDefault(); }}><button className="text-destructive underline">Batalkan</button></form>}</td>}</tr>)}</tbody></table>{!filteredRows.length && <p className="p-4 text-sm text-muted-foreground">Belum ada data.</p>}</div>
  </div>;
}
